const listaproduto = [
  {
    titulo: 'Shorts Masculino Em Sarja - Azul',
    genero: 'Masculino',
    categoria: 'Bermudas',
    faixa: 'R$50-R$99,99',
    tamanho: 'M',
    img: 'hrg-1',
    preco: 'R$59,99',
    parcelado: '2x R$29,99',
    id: 1,
  },
  {
    titulo: 'Regata Feminina Alças Largas Hering + Verena Smit - Preto',
    genero: 'feminino',
    categoria: 'Regatas',
    faixa: 'R$50-R$99,99',
    tamanho: 'M',
    img: 'hrg-2',
    preco: 'R$79,99',
    parcelado: '2x R$39,99',
    id: 2,
  },
  {
    titulo: 'Bermuda Feminina Ciclista Em Sarja - Bege',
    genero: 'feminino',
    categoria: 'Bermudas',
    faixa: 'R$100-R$199,99',
    tamanho: 'P',
    img: 'hrg-3',
    preco: 'R$119,99',
    parcelado: '3x R$39,99',
    id: 3,
  },
  {
    titulo: 'Calça Feminina Jeans Cigarrete Soft Touch - Azul',
    genero: 'feminino',
    categoria: 'Calças',
    faixa: 'R$100-R$199,99',
    tamanho: 'M',
    img: 'hrg-4',
    preco: 'R$159,99',
    parcelado: '5x R$31,99',
    id: 4,
  },
  {
    titulo: 'Blusa Feminina Gola Alta Manga Longa Com Elastano - Marrom',
    genero: 'feminino',
    categoria: 'Camisetas',
    faixa: 'R$50-R$99,99',
    tamanho: 'G',
    img: 'hrg-5',
    preco: 'R$89,99',
    parcelado: '2x R$44,99',
    id: 5,
  },
  {
    titulo: 'Calça Masculina Tapper Chino Em Sarja - Cinza',
    genero: 'Masculino',
    categoria: 'Calças',
    faixa: 'R$100-R$199,99',
    tamanho: 'M',
    img: 'hrg-6',
    preco: 'R$179,99',
    parcelado: '5x R$35,99',
    id: 6,
  },
  {
    titulo: 'Calça Menino Em Tecido Slim Chino - Azul',
    genero: 'Kids',
    categoria: 'Calças',
    faixa: 'R$50-R$99,99',
    tamanho: 'M',
    img: 'hrg-7',
    preco: 'R$79,99',
    parcelado: '2x R$39,99',
    id: 7,
  },
  {
    titulo: 'Camiseta Infantil Menino Snoopy Com Estampa - Verde',
    genero: 'Kids',
    categoria: 'Camisetas',
    faixa: 'R$20-R$49,99',
    tamanho: 'P',
    img: 'hrg-8',
    preco: 'R$39,99',
    parcelado: '2x R$19,99',
    id: 8,
  },
];
export default listaproduto;
