const listaprodutoCloth = [
  {
    titulo: 'Shorts masculino Em Sarja - Azul',
    genero: 'masculino',
    img: 'hrg-1',
    preco: 59.99,
    parcelado: '2x R$29,99',
    sku: 1,
    loja: 'clothefashion',
    filtro1: ['Bermudas'],
    filtro2: ['M', 'GG'],
    filtro3: 'R$50-R$99,99',
  },
  {
    titulo: 'Regata Feminina Alças Largas Hering + Verena Smit - Preto',
    genero: 'feminino',
    filtro3: 'R$50-R$99,99',
    img: 'hrg-2',
    preco: 79.99,
    parcelado: '2x R$39,99',
    sku: 2,
    loja: 'clothefashion',
    filtro1: ['Regatas'],
    filtro2: ['M'],
  },
  {
    titulo: 'Bermuda Feminina Ciclista Em Sarja - Bege',
    genero: 'feminino',
    filtro1: ['Bermudas'],
    filtro3: 'R$100-R$199,99',
    filtro2: ['P'],
    img: 'hrg-3',
    preco: 119.99,
    parcelado: '3x R$39,99',
    sku: 3,
    loja: 'clothefashion',
  },
  {
    titulo: 'Calça Feminina Jeans Cigarrete Soft Touch - Azul',
    genero: 'feminino',
    filtro1: ['Calças'],
    filtro3: 'R$100-R$199,99',
    filtro2: ['M'],
    img: 'hrg-4',
    preco: 159.99,
    parcelado: '5x R$31,99',
    sku: 4,
    loja: 'clothefashion',
  },
  {
    titulo: 'Blusa Feminina Gola Alta Manga Longa Com Elastano - Marrom',
    genero: 'feminino',
    filtro1: ['Camisetas'],
    filtro3: 'R$50-R$99,99',
    filtro2: ['P', 'G'],
    img: 'hrg-5',
    preco: 89.99,
    parcelado: '2x R$44,99',
    sku: 5,
    loja: 'clothefashion',
  },
  {
    titulo: 'Calça Masculina Tapper Chino Em Sarja - Cinza',
    genero: 'masculino',
    filtro1: ['Calças'],
    filtro3: 'R$100-R$199,99',
    filtro2: ['M'],
    img: 'hrg-6',
    preco: 179.99,
    parcelado: '5x R$35,99',
    sku: 6,
    loja: 'clothefashion',
  },
  {
    titulo: 'Calça Menino Em Tecido Slim Chino - Azul',
    genero: 'kids',
    filtro1: ['Calças'],
    filtro3: 'R$50-R$99,99',
    filtro2: ['M'],
    img: 'hrg-7',
    preco: 79.99,
    parcelado: '2x R$39,99',
    sku: 7,
    loja: 'clothefashion',
  },
  {
    titulo: 'Camiseta Infantil Menino Snoopy Com Estampa - Verde',
    genero: 'kids',
    filtro1: ['Camisetas'],
    filtro3: 'R$20-R$49,99',
    filtro2: ['P'],
    img: 'hrg-8',
    preco: 39.99,
    parcelado: '2x R$19,99',
    sku: 8,
    loja: 'clothefashion',
  },
];

export default listaprodutoCloth;
